# Autogenerated by nbdev

d = { 'settings': { 'branch': '0',
                'doc_baseurl': '/sen-ai',
                'doc_host': 'https://0.github.io',
                'git_url': 'https://github.com/0/sen-ai',
                'lib_path': 'sen_ai'},
  'syms': {'sen_ai.core': {'sen_ai.core.foo': ('core.html#foo', 'sen_ai/core.py')}}}
