# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/MLP.ipynb.

# %% auto 0
__all__ = ['path_data', 'path_gz', 'accuracy', 'report', 'Dataset']

# %% ../nbs/MLP.ipynb 2
import pickle,gzip,math,os,time,shutil,torch,matplotlib as mpl, numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from torch import tensor
from fastcore.test import test_close
torch.manual_seed(42)
path_data = Path("MNIST")
path_data.mkdir(exist_ok=True)
path_gz = path_data/'mnist.pkl.gz'

# %% ../nbs/MLP.ipynb 63
def accuracy(preds,targ):
    return (preds.argmax(1) == targ).float().mean()
    
    

# %% ../nbs/MLP.ipynb 64
def report(loss, preds, yb): print(f'{loss:.2f}, {accuracy(preds, yb):.2f}')

# %% ../nbs/MLP.ipynb 76
class Dataset():
    def __init__(self,x,y): self.x,self.y = x,y
    def __len__(self): return len(self.x)
    def __getitem__(self,i): return self.x[i],self.y[i]

# %% ../nbs/MLP.ipynb 92
from torch.utils.data import DataLoader, SequentialSampler, RandomSampler, BatchSampler
