# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Fashion_mnist.ipynb.

# %% ../nbs/Fashion_mnist.ipynb 1
from __future__ import annotations
import math,numpy as np,matplotlib.pyplot as plt
from operator import itemgetter
from itertools import zip_longest
import fastcore.all as fc

from torch.utils.data import default_collate

#from miniai.training import *
#!pip install miniai
import logging,pickle,gzip,os,time,shutil,torch,matplotlib as mpl
from pathlib import Path

from torch import tensor,nn,optim
from torch.utils.data import DataLoader
import torch.nn.functional as F
from datasets import load_dataset,load_dataset_builder

import torchvision.transforms.functional as TF
from fastcore.test import test_close

# %% auto 0
__all__ = ['inplace', 'collate_dict', 'show_image', 'subplots', 'get_grid', 'show_images']

# %% ../nbs/Fashion_mnist.ipynb 7
def inplace(f):
    def _f(b):
        f(b)
        return b
    return _f

# %% ../nbs/Fashion_mnist.ipynb 13
def collate_dict(ds):
    get = itemgetter(*ds.features)
    def _f(b): return get(default_collate(b))
    return _f

# %% ../nbs/Fashion_mnist.ipynb 26
@fc.delegates(plt.Axes.imshow, keep=True)
def show_image(im,ax=None,figsize=None,title = None,**kwargs):
    if fc.hasattrs(im,('cpu','permute','detach')):
        im = im.detach().cpu()
    if im.shape[0]>5 and len(im.shape) == 3:
        im = im.permute(1,2,0)
    if im.shape[-1]==1: im=im[...,0]
    if ax is None : _,ax = plt.subplots(figsize=figsize)
    ax.imshow(im,**kwargs)
    if title is not None: ax.set_title(title)
    ax.set_xticks([]) 
    ax.set_yticks([]) 
    ax.axis('off')
    return ax


# %% ../nbs/Fashion_mnist.ipynb 28
@fc.delegates(plt.subplots, keep=True)
def subplots(nrows:int=1, # Number of rows in returned axes grid
    ncols:int=1, # Number of columns in returned axes grid
    figsize:tuple=None, # Width, height in inches of the returned figure
    imsize:int=3, # Size (in inches) of images that will be displayed in the returned figure
    suptitle:str=None, # Title to be set to returned figure
    **kwargs):
    if figsize is None: figsize = (imsize*nrows,imsize*ncols)
    fig,ax = plt.subplots(nrows,ncols,figsize=figsize,**kwargs)
    if suptitle is not None: fig.suptitle(suptitle)
    if nrows*ncols==1: ax = np.array([ax])
    return fig,ax

# %% ../nbs/Fashion_mnist.ipynb 30
@fc.delegates(subplots)
def get_grid(
    n:int, # Number of axes
    nrows:int=None, # Number of rows, defaulting to `int(math.sqrt(n))`
    ncols:int=None, # Number of columns, defaulting to `ceil(n/rows)`
    title:str=None, # If passed, title set to the figure
    weight:str='bold', # Title font weight
    size:int=14, # Title font size
    **kwargs,
): # fig and axs
    "Return a grid of `n` axes, `rows` by `cols`"
    if nrows: ncols = ncols or int(np.floor(n/nrows))
    elif ncols: nrows = nrows or int(np.ceil(n/ncols))
    else:
        nrows = int(math.sqrt(n))
        ncols = int(np.floor(n/nrows))
    fig,axs = subplots(nrows, ncols, **kwargs)
    for i in range(n, nrows*ncols): axs.flat[i].set_axis_off()
    if title is not None: fig.suptitle(title, weight=weight, size=size)
    return fig,axs

# %% ../nbs/Fashion_mnist.ipynb 32
@fc.delegates(subplots)
def show_images(ims:list, # Images to show
                nrows:int|None=None, # Number of rows in grid
                ncols:int|None=None, # Number of columns in grid (auto-calculated if None)
                titles:list|None=None, # Optional list of titles for each image
                **kwargs):
    "Show all images `ims` as subplots with `rows` using `titles`"
    axs = get_grid(len(ims), nrows, ncols, **kwargs)[1].flat
    for im,t,ax in zip_longest(ims, titles or [], axs): show_image(im, ax=ax, title=t)
